### ISSUE TITLE
Warning: you should require 'minitest/autorun' instead.

### ISSUE THREAD

**Issue by amccloud** [ordinaryzelig/capybara_minitest_spec#9]
`capybara_minitest_spec` is causing this warning after upgrading to Rails 4.1.

```
Warning: you should require 'minitest/autorun' instead.
Warning: or add 'gem "minitest"' before 'require "minitest/autorun"'
From:
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247:in `require'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247:in `block in require'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:232:in `load_dependency'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247:in `require'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/minitest-5.3.3/lib/minitest/spec.rb:1:in `<top (required)>'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247:in `require'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247:in `block in require'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:232:in `load_dependency'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247:in `require'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/capybara_minitest_spec-1.0.1/lib/capybara_minitest_spec.rb:3:in `<top (required)>'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.6.1/lib/bundler/runtime.rb:76:in `require'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.6.1/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.6.1/lib/bundler/runtime.rb:72:in `each'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.6.1/lib/bundler/runtime.rb:72:in `block in require'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.6.1/lib/bundler/runtime.rb:61:in `each'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.6.1/lib/bundler/runtime.rb:61:in `require'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.6.1/lib/bundler.rb:132:in `require'
  /Users/amccloud/Pokertrip/pokeratlas/config/application.rb:5:in `<top (required)>'
  /Users/amccloud/Pokertrip/pokeratlas/Rakefile:5:in `require'
  /Users/amccloud/Pokertrip/pokeratlas/Rakefile:5:in `<top (required)>'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.3.1/lib/rake/rake_module.rb:28:in `load'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.3.1/lib/rake/rake_module.rb:28:in `load_rakefile'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.3.1/lib/rake/application.rb:683:in `raw_load_rakefile'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.3.1/lib/rake/application.rb:94:in `block in load_rakefile'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.3.1/lib/rake/application.rb:176:in `standard_exception_handling'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.3.1/lib/rake/application.rb:93:in `load_rakefile'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.3.1/lib/rake/application.rb:77:in `block in run'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.3.1/lib/rake/application.rb:176:in `standard_exception_handling'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.3.1/lib/rake/application.rb:75:in `run'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rake-10.3.1/bin/rake:33:in `<top (required)>'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/bin/rake:23:in `load'
  /Users/amccloud/.rbenv/versions/2.0.0-p353/bin/rake:23:in `<main>'
```

Similar issues with other gems
- https://github.com/thoughtbot/shoulda-matchers/issues/408
- https://github.com/rspec/rspec-rails/issues/758

**Comment by atmosx** [comment]
I'm getting this error using **ruby-2.2.2** and **rails-4.2.1**. Tried adding `gem 'minitest'` to `Gemfile` and/or adding `require 'minitest/autorun'` to `test/test_helper.rb` but still:

```
10:38:09 - INFO - Starting Spork for Test::Unit
Using TestUnit, Rails
Preloading Rails environment
Loading Spork.prefork block...
Spork is ready and listening on 8988!
10:38:13 - INFO - Spork server for Test::Unit successfully started
10:38:13 - INFO - Guard::Minitest 2.4.4 is running, with Minitest::Unit 5.6.1!
10:38:13 - INFO - Running: all tests
Warning: you should require 'minitest/autorun' instead.
Warning: or add 'gem "minitest"' before 'require "minitest/autorun"'
From:
  /Users/atma/.rvm/gems/ruby-2.2.2@crediteer/gems/spork-testunit-0.0.8/bin/testdrb:6:in `require'
  /Users/atma/.rvm/gems/ruby-2.2.2@crediteer/gems/spork-testunit-0.0.8/bin/testdrb:6:in `<top (required)>'
  /Users/atma/.rvm/gems/ruby-2.2.2@crediteer/bin/testdrb:23:in `load'
  /Users/atma/.rvm/gems/ruby-2.2.2@crediteer/bin/testdrb:23:in `<main>'
  /Users/atma/.rvm/gems/ruby-2.2.2@crediteer/bin/ruby_executable_hooks:15:in `eval'
  /Users/atma/.rvm/gems/ruby-2.2.2@crediteer/bin/ruby_executable_hooks:15:in `<main>'
Running tests with args ["./test/controllers/borrowers_controller_test.rb", "./test/models/borrower_test.rb", "./test/test_helper.rb"]...
------------------------------
Error executing ./test/controllers/borrowers_controller_test.rb ./test/models/borrower_test.rb ./test/test_helper.rb
undefined method `output=' for Minitest::Unit:Class
/Users/atma/.rvm/gems/ruby-2.2.2@crediteer/gems/spork-testunit-0.0.8/lib/spork/test_framework/test_unit.rb:9:in `run_tests'
/Users/atma/.rvm/gems/ruby-2.2.2@crediteer/bundler/gems/spork-224df492657e/lib/spork/run_strategy/forking.rb:13:in `block in run'
/Users/atma/.rvm/gems/ruby-2.2.2@crediteer/bundler/gems/spork-224df492657e/lib/spork/forker.rb:21:in `block in initialize'
/Users/atma/.rvm/gems/ruby-2.2.2@crediteer/bundler/gems/spork-224df492657e/lib/spork/forker.rb:18:in `fork'
/Users/atma/.rvm/gems/ruby-2.2.2@crediteer/bundler/gems/spork-224df492657e/lib/spork/forker.rb:18:in `initialize'
/Users/atma/.rvm/gems/ruby-2.2.2@crediteer/bundler/gems/spork-224df492657e/lib/spork/run_strategy/forking.rb:9:in `new'
/Users/atma/.rvm/gems/ruby-2.2.2@crediteer/bundler/gems/spork-224df492657e/lib/spork/run_strategy/forking.rb:9:in `run'
/Users/atma/.rvm/gems/ruby-2.2.2@crediteer/bundler/gems/spork-224df492657e/lib/spork/server.rb:49:in `run'
/Users/atma/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:1624:in `perform_without_block'
/Users/atma/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:1584:in `perform'
/Users/atma/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:1657:in `block (2 levels) in main_loop'
/Users/atma/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:1653:in `loop'
/Users/atma/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/drb/drb.rb:1653:in `block in main_loop'
------------------------------
Done.

10:38:14 - INFO - Guard is now watching at '/Users/atma/Code/Projects/crediteer'
```

Any other ideas?

Ty

**Comment by ordinaryzelig** [comment]
@atmosx, did you specifically add minitest to your Gemfile? You shouldn't need to because I believe Rails has it as a dependency and `require`s it correctly. If you add it to your Gemfile yourself, then Bundler may try to require `minitest` on startup, and so you get the error message. Could also be another gem that is trying to do the same thing.

**Comment by atmosx** [comment]
@ordinaryzelig Yes I did `require minitest` in the Gemfile. I have no idea what went wrong, but didn't work. However, I switched to Spring + MiniTest + Guard and everything works, tests are fairly fast.

**Comment by ordinaryzelig** [comment]
Just to be clear, you DO NOT need to include minitest in your Gemfile. Rails already requires it for you, and requires it correctly. If you manually put `gem 'minitest'` in your Gemfile, bundler may try to require it for you INCORRECTLY. Let Rails do it for you.

**Comment by atmosx** [comment]
I tried both actually, with minitest, without minitest, etc. But anyway, thanks for pointing that out.

**Comment by ordinaryzelig** [comment]
Occasionally using spring (or even just `bin/rake` without spring) does make a difference because of the way/order things startup.

**Comment by yassine75** [comment]
hi people can anyone of you help me please?

**Comment by ordinaryzelig** [comment]
@yassine75 what's up?
